version: "2"

volumes:
  data:
services:
  app:
    image: golang
    volumes:
      - ../../:/go/src/vcfConverter
    working_dir: /go/src/vcfConverter
    command: go run main.go
    ports:
      - "3000:80"
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golang_mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
    environment:
      MYSQL_ROOT_PASSWORD: root