version: '3'
services:
  app:
    build:
      context: ../../
      dockerfile: docker/Dockerfile
      target: prod
    volumes:
      - ../../:/app/
    ports:
      - "80:80"
    restart: unless-stopped
    environment: 
      DB_HOST_GOLANG: db
      DB_USER_GOLANG: root
      DB_PASSWORD_GOLANG: root
      DB_NAME_GOLANG: golang_mysql